FROM python:3.12-slim
WORKDIR /app
RUN pip install uv ibm-watsonxdata-mcp-server ibm-watsonx-data-intelligence-mcp-server
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY config.json /app/config.json
EXPOSE 12006 12007
